Provide deflateParams definition.
Error-202, 203
java.lang.InternalError: unknown error in checkDeflateStatus

Fix for changing the level and strategy dynamically using java APIs
setLevel() and setStrategy(). This can be changed in NX as well as
through Software fallback depending on NX state. The deflateParams
would set only supported strategy and level.

Signed-off-by: Sachin Monga <sachin.monga@ibm.com>